UPDATE `COLLECTIONS` SET `NAME` = 'English - Hindi' WHERE ID = 1;

INSERT INTO
 `COLLECTIONS` (`NAME`)
VALUES
	('English - Deutsch')
;

ALTER TABLE `BOXES` 
  ADD COLUMN `COLLECTION` int(4) NOT NULL
;

UPDATE `BOXES` SET `COLLECTION` = 1 WHERE ID = 1;
UPDATE `BOXES` SET `COLLECTION` = 1 WHERE ID = 2;
UPDATE `BOXES` SET `COLLECTION` = 1 WHERE ID = 3;
UPDATE `BOXES` SET `COLLECTION` = 1 WHERE ID = 4;

INSERT INTO
 `BOXES` (`NAME`, `COLLECTION`)
VALUES
	('Perm Box', 1),
	('Tages Box', 2),
	('Wochen Box', 2),
	('Monats Box', 2),
	('Jahres Box', 2),
	('Perma Box', 2)
;

ALTER TABLE `BOXES` 
  ADD CONSTRAINT `FK_COLLECTION`
  	FOREIGN KEY (`COLLECTION`)
    REFERENCES `COLLECTIONS`(`ID`)
;