DROP TABLE `EXAMPLEDATA`;

CREATE TABLE `CARDS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FRONT` varchar(500) NOT NULL,
  `BACK` varchar(500) NOT NULL,
 
  PRIMARY KEY (`ID`)
);

CREATE TABLE `BOXES` (
  `ID` int(4) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(500) NOT NULL,
 
  PRIMARY KEY (`ID`)
);

CREATE TABLE `COLLECTIONS` (
  `ID` int(4) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(500) NOT NULL,
 
  PRIMARY KEY (`ID`)
);

CREATE TABLE `TRAINING` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COLLECTION` int(4) NOT NULL,
  `CARD` int(4) NOT NULL,
  `BOX` int(4) NOT NULL,
  `LAST_UPDATED` TIMESTAMP NOT NULL
     DEFAULT CURRENT_TIMESTAMP 
     ON UPDATE CURRENT_TIMESTAMP,
  
  CONSTRAINT `FK_BOX`
  	FOREIGN KEY (`BOX`)
    REFERENCES `BOXES`(`ID`),

  CONSTRAINT `FK_CARD`
  	FOREIGN KEY (`CARD`)
    REFERENCES `CARDS`(`ID`),

  CONSTRAINT `FK_COLLECTION`
  	FOREIGN KEY (`COLLECTION`)
    REFERENCES `COLLECTIONS`(`ID`),

  PRIMARY KEY (`ID`)
);